# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='turl',
            fields=[
                ('urlid', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=1000)),
                ('surl', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=2000)),
                ('hits', models.IntegerField(default=0)),
            ],
        ),
    ]
